"""Add multi-tenancy and lead source

Revision ID: 800471ca6aec
Revises: 8a69e353327a
Create Date: 2026-05-24 22:33:19.572978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800471ca6aec'
down_revision: Union[str, Sequence[str], None] = '8a69e353327a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_intelligence', sa.Column('brokerage_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_ad_intelligence_brokerage_id'), 'ad_intelligence', ['brokerage_id'], unique=False)
    op.add_column('leads', sa.Column('brokerage_id', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('source', sa.String(), nullable=True))
    op.create_index(op.f('ix_leads_brokerage_id'), 'leads', ['brokerage_id'], unique=False)
    op.add_column('projects', sa.Column('brokerage_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_brokerage_id'), 'projects', ['brokerage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_brokerage_id'), table_name='projects')
    op.drop_column('projects', 'brokerage_id')
    op.drop_index(op.f('ix_leads_brokerage_id'), table_name='leads')
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'brokerage_id')
    op.drop_index(op.f('ix_ad_intelligence_brokerage_id'), table_name='ad_intelligence')
    op.drop_column('ad_intelligence', 'brokerage_id')
    # ### end Alembic commands ###
