"""Add AdIntelligence and improve Project

Revision ID: 8a69e353327a
Revises: 4a519d0097e9
Create Date: 2026-05-24 18:17:37.244804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a69e353327a'
down_revision: Union[str, Sequence[str], None] = '4a519d0097e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('builder', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('micro_market', sa.String(), nullable=True),
    sa.Column('offer', sa.Text(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('creative_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_intelligence_builder'), 'ad_intelligence', ['builder'], unique=False)
    op.create_index(op.f('ix_ad_intelligence_id'), 'ad_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_ad_intelligence_micro_market'), 'ad_intelligence', ['micro_market'], unique=False)
    op.add_column('projects', sa.Column('amenities_embeddings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'amenities_embeddings')
    op.drop_index(op.f('ix_ad_intelligence_micro_market'), table_name='ad_intelligence')
    op.drop_index(op.f('ix_ad_intelligence_id'), table_name='ad_intelligence')
    op.drop_index(op.f('ix_ad_intelligence_builder'), table_name='ad_intelligence')
    op.drop_table('ad_intelligence')
    # ### end Alembic commands ###
