"""Add conversation summary

Revision ID: acd197ae6177
Revises: b50d54ea7b20
Create Date: 2026-05-25 03:23:55.112360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd197ae6177'
down_revision: Union[str, Sequence[str], None] = 'b50d54ea7b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_summary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('conversation_summary')

    # ### end Alembic commands ###
