"""AI Lead Brain profiling v2

Revision ID: bba122c5072f
Revises: acd197ae6177
Create Date: 2026-05-25 04:58:27.789135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba122c5072f'
down_revision: Union[str, Sequence[str], None] = 'acd197ae6177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_pref', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('purchase_urgency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('intent_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('readiness_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('readiness_score')
        batch_op.drop_column('intent_type')
        batch_op.drop_column('purchase_urgency')
        batch_op.drop_column('location_pref')

    # ### end Alembic commands ###
